const projects = [
  {
    title: "Formidable",
    subTitle: "Forms creation and management App.",
    content: null,
    funcs: [
      "Confirm user creation with email.",
      "Create forms visually with drag and drop.",
      "Store and manage forms.",
      "Share forms with email or link.",
      "Access responses to a form.",
    ],
    imgs: "/imgs/formidable/1.png",
    imgAlt: "Formidable",
    tools: [
      "Reverse-engineer a complex module and build upon it's functionality.",
      "Build a Front-End with Next.js and Material.UI.",
      "Choose Server-side rendering vs Client-side rendering.",
      "Set-up a MongoAtlas database.",
      "Handle data in a non-relational DB.",
    ],
    live: false,
    repo: "https://github.com/FranciscoAlvarezRaineri/Formidalbe-front",
  },
  {
    title: "Figurita Repetida",
    subTitle: "Full Stack group eduicational E-Commerce",
    content: null,
    funcs: [
      "Create and log-in users and admins with session persistance.",
      "Search the stock with multiple parameters.",
      "Add and remove items to and from a cart.",
      "Manage a list of favourites and previous purchases.",
    ],
    imgs: "/imgs//fr/1.png",
    imgAlt: "Figurita Repetida",
    tools: [
      "Build a back-end with Express.js and Sequelize.",
      "User authentication and persistance.",
      "Set-up a PostreSQL DB.",
      "Establish relations and automate behaviours.",
      "Send emails with Nodemailer.",
    ],
    live: null,
    repo: "https://github.com/FranciscoAlvarezRaineri/FiguritaRepetida",
  },
  {
    title: "The Movie DataBase",
    subTitle: "Personal Full-Stack WIP.",
    content: null,
    funcs: ["Create and log-in users.", "Search for movies and shows."],
    imgs: "/imgs/tmdb/TMDB.png",
    imgAlt: "TMDB",
    tools: [
      "Build a front-end with React and Material.UI.",
      "Interact with an API.",
      "Set-up a Firebase project.",
      "Use Firebase Authentication and Firestore Database.",
    ],
    live: "https://tmdbnavigator.netlify.app",
    repo: "https://github.com/FranciscoAlvarezRaineri/TMDB",
  },
  {
    title: "Minesweeper",
    subTitle: "Self-imposed JavaScript challenge.",
    content: null,
    funcs: [
      "Play the clasic game Minesweeper.",
      "Read the instructions.",
      "Change the dificulty.",
      "Get a score.",
      "Inclues the traditional emoticon with reactions.",
    ],
    imgs: "/imgs/buscaminas/buscaminas.jpg",
    imgAlt: "Minesweeper",
    tools: [
      "Code a relatively complex JavaScript app.",
      "The joy of going from cero to hero",
    ],
    live: "https://elbuscaminas.netlify.app/",
    repo: "https://github.com/FranciscoAlvarezRaineri/minesweeper",
  },
  {
    title: "The Weather Channel",
    subTitle: null,
    content: null,
    funcs: [
      "Ask for the current weather in any city.",
      "Have it displayed in beatiful fashion.",
    ],
    imgs: "/imgs/wc/WC.jpg",
    imgAlt: "The Weather Channel",
    tools: ["Combine JavaScript, HTML and CSS.", "Interact with an API."],
    live: "https://elcanaldelclima.netlify.app/",
    repo: null,
  },
  {
    title: "To Do List",
    subTitle: null,
    content: null,
    funcs: [
      "Add and remove elements to the list.",
      "Re-oder and edit the elements.",
    ],
    imgs: "/imgs/todolist/Todolist.jpg",
    imgAlt: "To Do List",
    tools: [
      "Create and edit HTML components with JavaScript.",
      "Assigne and modify CSS styles with JavaScript",
    ],
    live: "https://cosapahacer.netlify.app/",
    repo: null,
  },
  {
    title: "Color Guessing Game",
    subTitle: null,
    content: null,
    funcs: [
      "Try to guess which color the RGB values represent.",
      "Select the difficulty.",
    ],
    imgs: "/imgs/colorsgame/colorsgame.jpg",
    imgAlt: "Color Guessing Game",
    tools: [
      "Code randomly generated numbers with changing constraints in JavaScript.",
      "Event handlers and alert messasges.",
    ],
    live: "https://adivina-adivinador.netlify.app/",
    repo: null,
  },
];

export default projects;
